core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls','website'),namespace='website')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop_index, name='index'),
]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # Add more paths here
]

ansible_control/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


    def __str__(self):
        return self.name

website/models.py
from django.db import models

# Create your models here.

ansible_control/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _

from .models import Product


def shop_index(request):
    products = Product.objects.all()

    context = {
        'page_title': _('Shop'),
        'products': products
    }

    return render(request, 'shop/index.html', context=context)

website/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'website/index.html')

shop/templates/shop/index.html
{% extends "website/base.html" %}
{% load i18n %}


{% block content %}
<div class="container text-center mb-5">
    <h2>{% trans "Shop" %}</h2>
</div>

<div class="container text-center">
    {% if products %}
    {% for product in products %}

    {% include "shop/product_card.html" %}

    {% endfor %}
    {% else %}
    <p>{% trans "There are no products available at this time. 😟" %}</p>
    {% endif %}
</div>
{% endblock %}

shop/templates/shop/product_card.html
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            {% if product.image %}
            <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="{{ product.name }}" height="50%">
            {% else %}
            <img src="https://via.placeholder.com/300" class="img-fluid rounded-start" alt="{{ product.name }}">
            {% endif %}
        </div>
        <div class="col-md-6">
            <div class="card-body">
                {% if product.name %}
                <h5 class="card-title">{{ product.name }}</h5>
                {% else %}
                <h5 class="card-title">Name</h5>
                {% endif %}
                {% if product.description %}
                <p class="card-text">{{ product.description|truncatewords:10 }}</p>
                {% else %}
                <p class="card-text">Description</p>
                {% endif %}

                {# <a href="{% url 'shop:product-detail' product.id %}" class="btn btn">View Product</a> #}

            </div>
        </div>
        <div class="col-md-2">
            {% if product.price %}

            <p class="card-text">{{ product.price|floatformat:2 }}€</p>
            {% else %}
            <p class="card-text">Price</p>
            {% endif %}
        </div>
    </div>
</div>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

website/templates/website/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if page_title %}
        {{page_title}}
        {% else %}
        Ansible
        {% endif %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous" defer></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous" defer></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body data-bs-theme="dark">
    {% include "website/navbar.html" %}

    {% if breadcrumbs %}
    <div class="container">
        {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs%}
    </div>
    {% endif %}

    {% block content %}

    {% endblock %}

    {% include "website/footer.html" %}

</body>

</html>

website/templates/website/footer.html
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <!--
            
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            
            -->
        </ul>
        <p class="text-center text-body-secondary"><a href="mailto:admin@example.com?subject=website contact">{{contact_email}}</a></p>
        <p class="text-center text-body-secondary">&copy; Jonne Saloranta 2024</p>
    </footer>
</div>

website/templates/website/index.html
{% extends "website/base.html" %}

{% block content %}
<div class="container">
    <h2>Home Page</h2>
    <p>Welcome to the home page of the website</p>
</div>
{% endblock %}

website/templates/website/navbar.html
{% load i18n %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3 mb-4 border-bottom">
        <a href="{% url 'website:index' %}" class="navbar-brand d-flex align-items-center">Ansible</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a href="{% url 'website:index' %}" class="nav-link fs-5">{% trans "Home" %}</a></li>
                <li class="nav-item"><a href="{% url 'shop:index' %}" class="nav-link fs-5">{% trans "Shop" %}</a></li>
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li class="nav-item"><a href="/admin" class="nav-link fs-5">{% trans "Dashboard" %} <i class="bi bi-speedometer"></i></a></li>
                {% endif %}
                {% endif %}
                {% if not user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'website:index' %}" class="nav-link fs-5">{% trans "Login" %}</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'website:index' %}" class="nav-link fs-5">{% trans "Logout" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>